"""empty message

Revision ID: 28d39e938857
Revises: None
Create Date: 2016-09-26 12:22:08.025256

"""

# revision identifiers, used by Alembic.
revision = '28d39e938857'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('bio1', sa.String(length=120), nullable=True))
    op.drop_column('User', 'bio')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('bio', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('User', 'bio1')
    ### end Alembic commands ###
